"""
Exports synthesised analysis to a formatted Word document.
Produces professional output suitable for board papers, briefings, and submissions.
"""
import io
from datetime import date
from docx import Document
from docx.shared import Pt, RGBColor, Inches, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
import re


def _add_heading(doc, text, level=1):
    h = doc.add_heading(text, level=level)
    h.runs[0].font.color.rgb = RGBColor(0x1a, 0x1a, 0x2e)
    return h


def _add_rule(doc):
    p = doc.add_paragraph()
    pPr = p._p.get_or_add_pPr()
    pBdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "6")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), "CCCCCC")
    pBdr.append(bottom)
    pPr.append(pBdr)
    return p


def _parse_markdown(doc, text):
    """Convert basic markdown to Word paragraphs."""
    lines = text.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i].rstrip()
        if not line:
            i += 1
            continue
        if line.startswith("## "):
            _add_heading(doc, line[3:], level=2)
        elif line.startswith("### "):
            _add_heading(doc, line[4:], level=3)
        elif line.startswith("# "):
            _add_heading(doc, line[2:], level=1)
        elif line.startswith("- ") or line.startswith("* "):
            doc.add_paragraph(line[2:], style="List Bullet")
        elif re.match(r"^\d+\. ", line):
            doc.add_paragraph(re.sub(r"^\d+\. ", "", line), style="List Number")
        elif line.startswith("**") and line.endswith("**"):
            p = doc.add_paragraph()
            run = p.add_run(line.strip("*"))
            run.bold = True
        else:
            p = doc.add_paragraph()
            # Handle inline bold **text**
            parts = re.split(r"\*\*(.*?)\*\*", line)
            for j, part in enumerate(parts):
                run = p.add_run(part)
                if j % 2 == 1:
                    run.bold = True
        i += 1


def build_research_doc(query, answer, sources, filters=None):
    """
    Build a Word doc from a research search result.
    Returns bytes (BytesIO buffer).
    """
    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin = Cm(2.5)
        section.bottom_margin = Cm(2.5)
        section.left_margin = Cm(3)
        section.right_margin = Cm(2.5)

    # Header
    header = doc.sections[0].header
    hp = header.paragraphs[0]
    hp.text = "Housing Intelligence Platform"
    hp.runs[0].font.color.rgb = RGBColor(0x99, 0x99, 0x99)
    hp.runs[0].font.size = Pt(9)
    hp.alignment = WD_ALIGN_PARAGRAPH.RIGHT

    # Title block
    title_p = doc.add_paragraph()
    title_run = title_p.add_run("Research Analysis")
    title_run.font.size = Pt(22)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(0x1a, 0x1a, 0x2e)

    doc.add_paragraph(f"Generated: {date.today().strftime('%d %B %Y')}")
    _add_rule(doc)

    # Research question
    _add_heading(doc, "Research Question", level=2)
    q_para = doc.add_paragraph(query)
    q_para.runs[0].italic = True

    if filters:
        doc.add_paragraph(f"Filters applied: {filters}")

    doc.add_paragraph()
    _add_rule(doc)

    # Synthesised analysis
    _add_heading(doc, "Synthesised Analysis", level=2)
    _parse_markdown(doc, answer)

    doc.add_page_break()

    # Sources table
    _add_heading(doc, f"Evidence Base ({len(sources)} sources)", level=2)
    table = doc.add_table(rows=1, cols=4)
    table.style = "Table Grid"
    hdr = table.rows[0].cells
    for i, col in enumerate(["#", "Title", "Year", "Agency"]):
        hdr[i].text = col
        hdr[i].paragraphs[0].runs[0].bold = True

    for i, s in enumerate(sources, 1):
        row = table.add_row().cells
        row[0].text = str(i)
        row[1].text = s.get("title", "")[:80]
        row[2].text = str(s.get("year", ""))
        row[3].text = s.get("source_agency", "")

    doc.add_paragraph()
    doc.add_paragraph(
        "Sources retrieved using semantic search across indexed AHURI, Housing Australia, "
        "Treasury, AIHW, Productivity Commission, ABS, and DSS publications.",
        style="Body Text"
    )

    # Footer note
    footer = doc.sections[0].footer
    fp = footer.paragraphs[0]
    fp.text = (
        f"Generated by Housing Intelligence Platform | {date.today().strftime('%d %B %Y')} | "
        "For internal use — verify citations before external publication"
    )
    fp.runs[0].font.size = Pt(8)
    fp.runs[0].font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf


def build_impact_doc(policy, answer, sources):
    """Build a Word doc from a policy impact analysis."""
    doc = Document()

    for section in doc.sections:
        section.top_margin = Cm(2.5)
        section.bottom_margin = Cm(2.5)
        section.left_margin = Cm(3)
        section.right_margin = Cm(2.5)

    title_p = doc.add_paragraph()
    run = title_p.add_run("Policy Impact Assessment")
    run.font.size = Pt(22)
    run.bold = True
    run.font.color.rgb = RGBColor(0x1a, 0x1a, 0x2e)

    doc.add_paragraph(f"Generated: {date.today().strftime('%d %B %Y')}")
    _add_rule(doc)

    _add_heading(doc, "Program Details", level=2)
    table = doc.add_table(rows=4, cols=2)
    table.style = "Table Grid"
    details = [
        ("Program", policy.get("event", "")),
        ("Year", str(policy.get("year", ""))),
        ("Investment", f"${policy.get('amount_bn', '')}B"),
        ("Type", policy.get("type", "").replace("_", " ").title()),
    ]
    for i, (k, v) in enumerate(details):
        row = table.rows[i].cells
        row[0].text = k
        row[0].paragraphs[0].runs[0].bold = True
        row[1].text = v

    doc.add_paragraph()
    _add_rule(doc)
    _add_heading(doc, "Impact Assessment", level=2)
    _parse_markdown(doc, answer)

    if sources:
        doc.add_page_break()
        _add_heading(doc, f"Evidence Base ({len(sources)} sources)", level=2)
        table2 = doc.add_table(rows=1, cols=3)
        table2.style = "Table Grid"
        hdr = table2.rows[0].cells
        for i, col in enumerate(["Title", "Year", "Agency"]):
            hdr[i].text = col
            hdr[i].paragraphs[0].runs[0].bold = True
        for s in sources:
            row = table2.add_row().cells
            row[0].text = s.get("title", "")[:80]
            row[1].text = str(s.get("year", ""))
            row[2].text = s.get("source_agency", "")

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf
